<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>EnhancementShamanBot</RootNamespace>
    <AssemblyName>EnhancementShamanBot</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BloogBot\BloogBot.csproj" />
  </ItemGroup>

</Project>
