<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>ArcaneMageBot</RootNamespace>
    <AssemblyName>ArcaneMageBot</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BloogBot\BloogBot.csproj" />
  </ItemGroup>

</Project>
